/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "MainComponent.h"

// This class is our window
class MainWindow : public DocumentWindow
{
public:
    //============================================================================================
    MainWindow() : DocumentWindow("Swivel", Colours::lightgrey, DocumentWindow::allButtons, true)
    {
        setContentOwned(new MainComponent(), true);
        setResizable(true, true);
        setVisible(true);
    }
    ~MainWindow() {}
    
    //=============================================================================================
    void closeButtonPressed()
    {
        // user has pressed the close button, so we want to exit
        JUCEApplication::quit();
    }
};

//==============================================================================
class SwivelAutotuneApplication  : public JUCEApplication
{
public:
    //==============================================================================
    SwivelAutotuneApplication() {}

    const String getApplicationName()       { return ProjectInfo::projectName; }
    const String getApplicationVersion()    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed()       { return true; }

    //==============================================================================
    void initialise (const String& commandLine)
    {
        // actually make a window
        mainWindow = new MainWindow();
    }

    void shutdown()
    {
        // set scoped ptr to null destroys the object it points to
        mainWindow = 0;
    }

    //==============================================================================
    void systemRequestedQuit()
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& commandLine)
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }
    
private:
    // a pointer to the window
    ScopedPointer<MainWindow> mainWindow;
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (SwivelAutotuneApplication)
